(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
  (define (empty-queue?)
    (null? front-ptr))
  (define (front-queue item)
    (bkpt)
    (if (empty-queue)
        (error "empty queue" '())
        (car (front-ptr))))
  (define (insert-queue! item)
    (let ((new-pair (cons item '())))
      (cond ((empty-queue?)
             (set! front-ptr new-pair)
             (set! rear-ptr new-pair))
            (else
             (set-cdr! rear-ptr new-pair)
             (set! rear-ptr new-pair)))))
  (define (delete-queue!)
    (cond ((empty-queue?)
           (error "empty queue" '()))
          (else
           (set! front-ptr (cdr front-ptr)))))
  (define (print-queue)
    (begin
      (display front-ptr)))
  (define (dispatch signal)
    (cond ((eq? signal 'insert-queue!) 
           insert-queue!)
          ((eq? signal 'delete-queue!)
           delete-queue!)
          ((eq? signal 'print-queue)
           print-queue)
          ((eq? signal 'front-queue)
           front-queue)))
  dispatch))

(define q (make-queue))
