;; Some unclassified functions

(define (make-account balance) 
  (define (withdraw amount)
    (if (<= amount balance)
	(begin (set! balance (- balance amount))
	       balance)
	"insufficient balance"))
  (define (deposit amount)
    (if (> amount 0)
	(begin (set! balance (+ balance amount))
	       balance)
	"Insufficient funds"))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "adsf" m))))
  dispatch)
  

(define (make-accumulator initsum)
  (accumulator initsum))
	   
(define (accumulator sum)
  (lambda (count)
    (set! sum (+ count sum))
    sum))

(define (make-m count f)
  (define (inc-counter)
    (set! count (+ 1 count)))
  (define (reset)
    (set! count 0))
  (define (how-many-calls)
    count)
  (define (dispatch msg) 
    (cond ((eq? msg 'reset) (reset))
	  ((eq? msg 'how-many-calls) (how-many-calls))
	  (else (begin (inc-counter) (f msg)))))
  dispatch)
  
(define (make-monitored f)
  (make-m 0 f))
